### ISSUE TITLE
Crashing When Window Is Hidden

### ISSUE THREAD

**Issue by atom0s** [NeoforceControls/XNA#1]
When drawing a single window and it is closed / hidden, Neoforce seems to crash with an object disposed exception.

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'RenderTarget2D'.
   at Microsoft.Xna.Framework.Helpers.CheckDisposed(Object obj, IntPtr pComPtr)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTargets(RenderTargetBinding* pBindings, Int32 renderTargetCount)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(RenderTarget2D renderTarget)
   at TomShane.Neoforce.Controls.Manager.Draw(GameTime gameTime) in c:\Users\atom0s\Documents\Visual Studio 2012\Projects\Detox\Detox\NeoforceControls\Code\Manager.cs:line 1238
   at TomShane.Neoforce.Controls.Manager.BeginDraw(GameTime gameTime) in c:\Users\atom0s\Documents\Visual Studio 2012\Projects\Detox\Detox\NeoforceControls\Code\Manager.cs:line 1210
   at Detox.Hooks.Xna.PreDraw(GameTime gameTime) in c:\Users\atom0s\Documents\Visual Studio 2012\Projects\Detox\Detox\Detox\Hooks\Xna.cs:line 250
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Microsoft.Xna.Framework.Game.Run()
```

Steps to reproduce:
1. Create a simple project.
2. Create a simple window control. (And add to the manager.)
3. Run application and close the Gui window.
4. Resize the application window. (Maximize / Minimize / Resize all work to crash it.)
If a second window is being drawn it seems to not crash. But if all elements are hidden, it will.

(Reposting from Codeplex due to the move.)

**Comment by Grimston** [comment]
Having no problem with the following code...

``` C#
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using TomShane.Neoforce.Controls;

namespace NeoforceTest
{
    public class Game1 : Microsoft.Xna.Framework.Game
    {
        GraphicsDeviceManager graphics;
        Manager NeoManager;
        Window NeoWindow;

        public Game1()
        {
            graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";
            IsMouseVisible = true;
            Window.AllowUserResizing = true;
        }

        protected override void LoadContent()
        {
            NeoManager = new Manager(this);
            NeoManager.AutoCreateRenderTarget = true;
            NeoManager.AutoUnfocus = true;
            NeoManager.Initialize();

            NeoWindow = new Window(NeoManager);
            NeoWindow.Init();

            NeoManager.Add(NeoWindow);
        }

        protected override void Update(GameTime gameTime)
        {
            NeoManager.Update(gameTime);

            base.Update(gameTime);
        }

        protected override void Draw(GameTime gameTime)
        {
            NeoManager.BeginDraw(gameTime);
            GraphicsDevice.Clear(Color.CornflowerBlue);

            NeoManager.EndDraw();
            base.Draw(gameTime);
        }
    }
}
```

Are you using the latest version?

**Comment by atom0s** [comment]
Yes I have latest. Do you have a way I can contact you privately. I can explain things a bit more in depth with what I am doing.

**Comment by Grimston** [comment]
Sure, just send me a email to nathan@npipes.net

Edit: forgot the @ Symbol

**Comment by atom0s** [comment]
Really late response to this but seems I found a work-around for this.

I register to the Game windows 'ClientSizeChanged' event and set the render target of the manager to null anytime its invoked. It prevents the crash from happening and the manager properly recreates the render target without issue.

**Comment by Grimston** [comment]
Better late then never.

That does make sense, especially since your project is a little different then the normal use. the GraphicsDevice is managed from the underlying program.

I know I was looking into something but I have forgotten what it was. was it stack panels inside stack panels?

**Comment by atom0s** [comment]
Yeah stackpanels seem broken still. They don't properly stack objects.
For example I have this:
```c#Code removed..

```

The resulting window looks like this created:
Screenshot removed..

Edit: Posted the wrong example sorry lol.. I'll make a new issue for this.
```

**Comment by Grimston** [comment]
First thing I noticed is your not adding the stack panel to the Window and your not adding the group boxs to the stack panel.

-------- Original message --------

**Comment by atom0s** [comment]
Yeah that was the wrong code example, I copied some old code instead of the new one. Sorry about that.

**Comment by Grimston** [comment]
Ah okay, no problem.

-------- Original message --------
